import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'chat',
  description: 'Generated by create next app',
}
export default function ChatLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {


    return (
      <>
        {children}
      </>
    )
  }